spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localdb
    username: root
    password: 1234
  h2:
    console:
      enabled: true
  profiles:
    active: local
handlebars:
  suffix: .html
  enabled: true
security:
  jwt:
    token:
      secret-key: my_secret_is_secret
      expire-length: 3600000